### ISSUE TITLE
(Logger) Fault when browser returns one line in stack trace

### ISSUE THREAD

**Issue by bukharin** [jitsi/jitsi-meet-logger#3]
Hi,

Issue is here: https://github.com/jitsi/jitsi-meet-logger/blob/master/lib/Logger.js#L88 when `stack.length === 1`

![image](https://user-images.githubusercontent.com/3126568/45620736-4c6f7100-ba97-11e8-9081-90d0b0fb74fa.png)

**Comment by paweldomas** [comment]
OMG we're such amateurs, thanks for the report !

**Comment by bukharin** [comment]
@paweldomas any plans to fix this?

**Comment by sproot** [comment]
?

**Comment by paweldomas** [comment]
yes, I plan to fix it. Sorry forgot about that issue

**Comment by virtuacoplenny** [comment]
Could I get an example provided of how to repro the issue? I'm not familiar with stack trace parsing and I've been unable to get logger to generate a one-line stack trace.

**Comment by saghul** [comment]
Fixed in #9
